version: "3.7"

services:
  backend:
    image: golang:1.15
    environment:
      DDAPI_TODO_SECRET: $DDAPI_TODO_SECRET
      DDAPI_TODO_DB: $DDAPI_TODO_DB
      DDAPI_TODO_ISS: $DDAPI_TODO_ISS
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    working_dir: "/app"
    command: ["bash", "-c", "go run main.go"]

  frontend:
    image: node:12
    environment:
      DDAPI_TODO_SECRET: $DDAPI_TODO_SECRET
      DDAPI_BACKEND_URL: "http://localhost:8080/login"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    working_dir: "/app"
    command: ["bash", "-c", "npm start"]
