// DO NOT EDIT THIS FILE: this is an auto-generate file
export const DDAPI_SIGNATURES = {
	"get-lists-by-sub_sql": "kgdo6ibIlL4zb7sfSV9us5Xv/LSMCzh7KamXBiu5IC8=",
	"get-lists-by-sub_params_schema": "rpZ9kviDrYSQrzi8N+fyI2ugQex0/C2P/VPnktSb5TA=",
};