// DO NOT EDIT THIS FILE: this is an auto-generate file
export const DDAPI_SIGNATURES = {
	"get-lists-by-sub_sql": "0QwM3MZs5wS9MXdU/WBLd1vUZI03r06izaArtrs07tA=",
	"get-lists-by-sub_params_schema": "waOUD+OcnTWMltCsAZem6cdPe43cC0Mdp3feMLPRXcM=",
};