// DO NOT EDIT THIS FILE: this is an auto-generate file
export const DDAPI_SIGNATURES = {
	// src/hooks/ddapi.js
	"list-insert_sql": "KrxQ8ljUBMYXMQ+31iDJVBVTrrOF+czx+Cv672toZTM=",
	"list-insert_params_schema": "tqaz3YJeoipomI2E0IN0fxX+G8irjn1PuvEv0rK8020=",
};